//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace databasemvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mytable
    {
        public int Roll_No { get; set; }
        public string Student_Name { get; set; }
        public int Student_Age { get; set; }
        public string Student_Location { get; set; }
        public Nullable<long> Phone_No { get; set; }
    }
}
